name: 📚 Deploy MkDocs
on:
  push:
    branches:
      - main

jobs: 
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout ${{ github.repository }}
        uses: actions/checkout@v3

      - name: 🐍 Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📄 Install Material for MkDocs
        run: pip install mkdocs-material
        
      - name: 🚀 Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
