name: 🚀 Release

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: 🔼 Bump release version
        id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}
          default_bump: "minor"
          custom_release_rules: "breaking:major:💣 Breaking Changes,feat:minor:✨ Features,fix:patch:💣 Bug Fixes,docs:patch:📰 Docs,chore:patch:🎨 Chore,pref:patch:🎈 Performance improvements,refactor:patch:🧹 Refactoring,build:patch:🔍 Build,ci:patch:🔍 CI,revert:patch:⏪ Revert,style:patch:🧹 Style,test:patch:👀 Test"
      - name: "☕ Setup Zulu JDK17"
        uses: actions/setup-java@v3.0.0
        with:
          distribution: "zulu"
          java-version: "17"
      - name: 🐘 Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: 📥 Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          path: project
      - name: ⌛ Restore caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 🐘 Run Gradle command
        run: |
          cd project
          gradle build
          mv build/libs/*.jar build/libs/vcspeaker-kt.jar
      - name: 🗃️ Publish Release on main
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ env.project_version }}
          files: |
            project/build/libs/vcspeaker-kt.jar
      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 📥 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Build Docker image
        env:
          project_version: ${{ steps.version.outputs.new_version }}
        uses: docker/build-push-action@v5
        with:
          context: ./project
          push: true
          tags: |
            ghcr.io/jaoafa/vcspeaker-kt:latest
            ghcr.io/jaoafa/vcspeaker-kt:${{ env.project_version }}